name: Voyage Analytics CI/CD

on:
  push:
    branches:
      - master

jobs:

  backend-ci:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install backend dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ${{ github.workspace }}/requirements.txt

    - name: Set correct MLflow path
      run: |
        echo "MLFLOW_TRACKING_URI=file:${{ github.workspace }}/mlruns" >> $GITHUB_ENV
        echo "MLFLOW_REGISTRY_URI=file:${{ github.workspace }}/mlruns" >> $GITHUB_ENV
        echo "MLFLOW_EXPERIMENT_NAME=ci-test" >> $GITHUB_ENV

    - name: Verify mlruns exists
      run: |
        ls -R ${{ github.workspace }}/mlruns || echo "mlruns folder not found"

    - name: Test backend import
      working-directory: ${{ github.workspace }}
      run: |
        export PYTHONPATH=${{ github.workspace }}
        python -c "import app.main"

  frontend-ci:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install frontend dependencies
      run: |
        python -m pip install --upgrade pip
        pip install streamlit

    - name: Test Streamlit app import
      working-directory: ${{ github.workspace }}
      run: |
        python -c "import streamlit_app"